In [1]:
import numpy as np
print(np.__version__)


2.2.6


In [4]:
arr = np.random.randint(1,50,size=10)



In [5]:
arr


array([15, 37, 37,  8, 34,  9, 27, 48, 23, 26], dtype=int32)

In [6]:
np.mean(arr)

np.float64(26.4)

In [7]:
arr1= [[1],[2],[3]]

In [8]:
arr1_np = np.array(arr1)

In [9]:
arr2 = [[1],[2],[3]]

In [10]:
arr2_np = np.array(arr2)

In [11]:
np.add(arr1_np,arr2_np)

array([[2],
       [4],
       [6]])

In [15]:
arr_rand = np.random.randint(1,100,size=20)

In [16]:
arr_rand


array([99, 97, 38, 33, 23, 59, 25, 90, 59, 33, 33, 65, 45,  6, 91, 27,  4,
       19, 87, 87], dtype=int32)

In [19]:
arr_filter = arr_rand[arr_rand>50]


In [20]:
arr_filter

array([99, 97, 59, 90, 59, 65, 91, 87, 87], dtype=int32)

In [21]:
arr_random = [1,2,3,4,5,6,7,8,9,10]

In [22]:
arr_random_np = np.array(arr_random)

In [23]:
arr_random_np = np.random.shuffle(arr_random_np)

In [24]:
arr_random_np

array([ 8,  7,  6, 10,  3,  1,  9,  5,  2,  4])